[package]
name = "amber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14.0"
kanal = "0.1.0-pre8"
once_cell = "1.19.0"
priority-queue = "1.4.0"
ref-cast = "1.0.22"
tokio = "1.36.0"
